spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/task
    username: root
    password: 1234
    initialization-mode: always  # schema.sql ?? data.sql ?? ??

  jpa:
    hibernate:
      ddl-auto: update  # ???: create, create-drop, update ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  # Thymeleaf ??
  thymeleaf:
    cache: false  # ??? ??? ?? ???? (Hot Reload)


  messages:
    basename: messages/ValidationMessages
    encoding: UTF-8

